# Generated by Django 2.1.5 on 2019-04-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='img/image_laptop.jpg', upload_to='products/'),
            preserve_default=False,
        ),
    ]
